name: Build NoProximityCall

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Theos
        shell: bash
        run: |
          bash -c "$(curl -fsSL https://raw.githubusercontent.com/roothide/theos/master/bin/install-theos)"

      - name: Install iOS SDK
        shell: bash
        run: |
          mkdir -p "$THEOS/sdks"

          curl -L \
            "https://github.com/theos/sdks/releases/latest/download/iPhoneOS16.5.sdk.tar.xz" \
            -o /tmp/iPhoneOS16.5.sdk.tar.xz

          tar -xJf /tmp/iPhoneOS16.5.sdk.tar.xz \
            -C "$THEOS/sdks"

      - name: Build RootHide DEB
        shell: bash
        run: |
          export THEOS="$HOME/theos"

          make clean

          make package \
            FINALPACKAGE=1 \
            THEOS_PACKAGE_SCHEME=roothide

      - name: Show package
        shell: bash
        run: |
          echo "===== Generated packages ====="
          ls -lah packages/

      - name: Upload DEB
        uses: actions/upload-artifact@v4
        with:
          name: NoProximityCall-RootHide
          path: packages/*.deb
          if-no-files-found: error
